# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Hemingway"
license = "MIT"
licenselink = "https://github.com/JoshuaCrewe/hemingway/blob/master/LICENSE.md"
description = "Really minimal blog theme for hugo"
homepage = "https://github.com/JoshuaCrewe/hemingway"
tags = ["blog"]
features = ["html5", "css3", "lazy-loading"]
min_version = 0.32

[author]
  name = "Joshua Crewe"
  homepage = "https://github.com/JoshuaCrewe"
