baseurl = "https://www.joshuacrewe.co.uk"
languageCode = "en"
title = "Joshua Crewe"
theme = "hemingway"
copyright = ""
description = "Notes from a human developer"
keywords = ["developer", "cornwall"]

[taxonomies]
tag = "tags"
category = "categories"

[params]

[[params.social]]
url = "https://github.com/joshuaCrewe"
ion_icon = "ion-social-github"

[[params.social]]
url = "https://twitter.com/joshua_crewe"
ion_icon = "ion-social-twitter"

[[params.social]]
url = "/index.xml"
ion_icon = "ion-social-rss"
